#!/usr/bin/env bash
# bin/detect <build-dir>

BUILD_DIR=$1

if [ ! -f "$BUILD_DIR/requirements.txt" ] && [ ! -f "$BUILD_DIR/setup.py" ] && [ ! -f "$BUILD_DIR/Pipfile" ]; then
  exit 1
fi

echo Python
exit 0
